// Centralized list of all Secretarias for use across the application

export const SECRETARIAS = [
    'SVCS - Secretaria do Verde',
    'SVCS - Gestão de Resíduos',
    'SVCS - Bem-estar Animal',
    'SRC - Receita',
    'SIURB - Infraestrutura',
    'SCT - Cultura e Turismo',
    'SDH - Direitos Humanos',
    'SDH - Juventude',
    'SDH - Mulher',
    'SDH - Acessibilidade',
    'SDH - Igualdade Racial',
    'SDH - Diversidade',
    'SCTI - Tecnologia e Inovação',
    'SGE - Gestão',
    'SS - Saúde',
    'SE - Educação',
    'SDET - Des. Econômico e Trabalho',
    'CFSS - Fundo Social',
    'CPDC - Procon',
    'SH - Habitação',
    'SDS - Des. Social',
    'SDS - Defesa Civil',
    'SDS - Idoso',
    'SCC - Casa Civil',
    'CGP - Chefia de Gabinete',
    'SAR',
    'SDU',
    'SEL - Esportes',
    'SJC - Justiça',
    'SFI - Finanças',
    'SEMOB',
    'SJCP - Procuradoria',
    'Controladoria',
    'Ouvidoria',
    'Segurança',
];
